name: Curl API Daily

on:
  schedule:
    - cron: '0 0 * * *'  # At 00:00 UTC daily
  workflow_dispatch:       # Manual trigger

jobs:
  curl-api:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Cloudflared tunnel API
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://simple-cron-test.onrender.com/
