name: Curl API Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Manual trigger

jobs:
  curl-api:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Cloudflared tunnel API
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://backgrounds-spokesman-tgp-acer.trycloudflare.com/
